# conda env create -f environment.yml
name: stv_sdap_notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11.4
  - requests
  - jupyter
  - ipykernel
  - ipywidgets
  - pillow
  - urllib3
  - matplotlib
  - pandas
  - numpy
  - xarray
  - fiona
  - cartopy
  - tabulate
  - owslib
  - geopandas
  - ipyleaflet
  - shapely
